spring:
  profiles:
    active:
    - local

---

spring:
  profiles:
  - local
         
  datasource:
    url: jdbc:mysql://localhost:3306/shoppingmall?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  servlet:
      multipart:
        max-file-size: 1000MB
        max-request-size: 1000MB        
        enabled: true      
        file-size-threshold: 1MB
        location: C:/Temp
        
  devtools:
    livereload:
      enabled: true
    restart:
      log-condition-evaluation-delta: false
      
server:
 port: 9000
    
 servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
       
    session: 
      timeout: 7200
 error:
      whitelabel:
        enabled: false

logging:
  config: classpath:logback-spring.xml  

mybatis:
  type-aliases-package: com.shoppingmall.example.domain
  mapper-locations: mapper/**/*.xml